# Dictionary containing all the KPIs mentioned
kpi_dictionary = {
    "Financial KPIs": {
        "Total Revenue": "Total income generated by the company from its operations.",
        "Revenue Growth Rate": "Percentage increase in revenue over a specific period.",
        "Recurring Revenue (ARR/MRR)": "Annual or monthly recurring revenue generated by subscriptions or recurring customers.",
        "Revenue per Customer": "Average revenue earned per customer over a specific period.",
        "Gross Profit": "Total revenue minus the cost of goods sold (COGS).",
        "Gross Margin": "Gross profit as a percentage of total revenue.",
        "Net Profit": "Total revenue minus all expenses, taxes, and costs.",
        "Net Profit Margin": "Net profit as a percentage of total revenue.",
        "EBITDA": "Earnings before interest, taxes, depreciation, and amortization.",
        "Operating Profit Margin": "Operating income as a percentage of revenue."
    },
    "Cost and Expense KPIs": {
        "Cost of Goods Sold (COGS)": "Direct costs of producing goods or services sold by the company.",
        "Operating Expenses (OPEX)": "Expenses incurred during normal business operations.",
        "Cost-to-Revenue Ratio": "Operating expenses as a proportion of total revenue."
    },
    "Cash Flow KPIs": {
        "Free Cash Flow (FCF)": "Cash generated after accounting for capital expenditures.",
        "Operating Cash Flow": "Cash generated from regular business operations.",
        "Cash Conversion Cycle (CCC)": "Time taken to convert inventory into cash through sales."
    },
    "Balance Sheet KPIs": {
        "Total Assets": "Total value of assets owned by the company.",
        "Total Liabilities": "Total value of liabilities owed by the company.",
        "Equity": "Difference between total assets and total liabilities.",
        "Debt-to-Equity Ratio": "Measure of financial leverage calculated by dividing total liabilities by equity.",
        "Current Ratio": "Measure of liquidity calculated by dividing current assets by current liabilities."
    },
    "Market KPIs": {
        "Market Capitalization": "Total market value of a company's outstanding shares.",
        "Enterprise Value (EV)": "Measure of a company's total value, including debt and equity.",
        "Price-to-Earnings (P/E) Ratio": "Valuation ratio comparing a company's current share price to its earnings per share."
    },
    "Performance KPIs": {
        "Return on Assets (ROA)": "Net income as a percentage of total assets.",
        "Return on Equity (ROE)": "Net income as a percentage of shareholder's equity.",
        "Asset Turnover Ratio": "Efficiency ratio that shows how effectively assets are used to generate revenue."
    },
    "Customer KPIs": {
        "Customer Acquisition Cost (CAC)": "Cost associated with acquiring a new customer.",
        "Lifetime Value (LTV)": "Predicted revenue a customer will generate during their lifetime.",
        "LTV-to-CAC Ratio": "Comparison of the lifetime value of a customer to the cost of acquiring them."
    }
}

def get_kpi_list():
    kpi_list = []
    for category in kpi_dictionary.values():
        kpi_list.extend(category.keys())
    return kpi_list
